-- Réplica PICCOLI × SIMBAL — grafo documental
-- Estrutura desenhada para manter dados de leitura e remissão no Supabase.
-- Não armazenar service_role, tokens do Google Drive ou conteúdo sigiloso no banco público.

create table if not exists public.case_nodes (
  id text primary key,
  node_type text not null check (node_type in ('document','fact','page','ground')),
  roman text,
  label text not null,
  subtitle text,
  reference_text text,
  drive_url text,
  grounds text[] not null default '{}',
  strength text not null default 'context' check (strength in ('direct','strong','context','caution')),
  use_text text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.case_edges (
  id bigint generated by default as identity primary key,
  source_id text not null references public.case_nodes(id) on delete cascade,
  target_id text not null references public.case_nodes(id) on delete cascade,
  kind text not null default 'support' check (kind in ('direct','support')),
  label text,
  created_at timestamptz not null default now(),
  unique(source_id,target_id,label)
);

create table if not exists public.priority_chains (
  id bigint generated by default as identity primary key,
  title text not null,
  chain text not null,
  description text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists case_nodes_type_idx on public.case_nodes(node_type);
create index if not exists case_nodes_grounds_gin on public.case_nodes using gin(grounds);
create index if not exists case_edges_source_idx on public.case_edges(source_id);
create index if not exists case_edges_target_idx on public.case_edges(target_id);

alter table public.case_nodes enable row level security;
alter table public.case_edges enable row level security;
alter table public.priority_chains enable row level security;

-- A interface usa somente leitura. O conteúdo documental continua no Google Drive,
-- preservando as permissões originais do Drive; o Supabase armazena somente metadados/links.
-- Esta política pode ser trocada por acesso autenticado antes do deploy definitivo, se desejado.
drop policy if exists "public read case_nodes" on public.case_nodes;
create policy "public read case_nodes" on public.case_nodes for select to anon, authenticated using (true);

drop policy if exists "public read case_edges" on public.case_edges;
create policy "public read case_edges" on public.case_edges for select to anon, authenticated using (true);

drop policy if exists "public read priority_chains" on public.priority_chains;
create policy "public read priority_chains" on public.priority_chains for select to anon, authenticated using (true);

-- Nenhuma policy de INSERT/UPDATE/DELETE é criada para anon/authenticated.
-- Escritas devem ocorrer por migration/SQL administrativo.
